### ISSUE TITLE
replace unittest dependency by test

### ISSUE THREAD

**Issue by rspilker** [renggli/dart-junit#4]
According to the [unittest documentation](https://pub.dartlang.org/packages/unittest) `unittest` has been deprecated and replaced by 'test'.

In my project I use `test` and cannot use `junitconfiguration` as a result :disappointed:

**Comment by renggli** [comment]
I looked at this recently. The problem is that `test` does not support the necessary callbacks for a custom output format as provided by this package. We will have to see, if the file format could be integrated into the official package instead.

**Comment by renggli** [comment]
Marking as obsolete, this package is no longer in use.
